### ISSUE TITLE
Chrome Dev Editor still use legacy core-element

### ISSUE THREAD

**Issue by s850042002** [googlecodelabs/polymer-webgl-visualization#2]
Chrome Dev Editor Version 0.22.3520
When you open a new project with JavaScript web app (using Polymer paper elements), index.html shows

```
<link rel="import" href="bower_components/core-icons/core-icons.html">
<link rel="import" href="bower_components/core-toolbar/core-toolbar.html">
```

I corrected it with

```
<link rel="import" href="bower_components/iron-icons/iron-icons.html">
<link rel="import" href="bower_components/paper-toolbar/paper-toolbar.html">
```

I still got these errors in the console, and the app's layout is incorrect.

```
Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic' because it violates the following Content Security Policy directive: "style-src 'self' blob: filesystem: data: chrome-extension-resource: 'unsafe-inline'".

index.html:1 Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Roboto+Mono:400,700' because it violates the following Content Security Policy directive: "style-src 'self' blob: filesystem: data: chrome-extension-resource: 'unsafe-inline'".

/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
```

**Comment by brendankenny** [comment]
Hmm, are you sure that your Chrome Dev Editor has updated? The default "JavaScript web app (using Polymer paper elements)" was updated to support Polymer 1.0 (and the associated `iron-icons`, etc) back in https://github.com/GoogleChrome/chromedeveditor/pull/3968, which should definitely be used for any new projects it creates.

Since you mentioned that you're on version  0.22.3520 I assume you did check this (in about:extensions), but just wanted to check. If you close the CDE, click "Update extensions now" on about:extensions, reopen the editor, then create a new app, you should see the correct template.

Beyond that, this is probably a bug for the Chrome Dev Editor project itself (https://github.com/GoogleChrome/chromedeveditor).

Good news for the codelab though: for the second step, you delete all the default imports anyways and use only ones needed for the codelab, so this shouldn't be an issue if you continue.
